#!/bin/bash

############################################################
# このファイルを作成後、chmod +x alphafoldで実行権限を付加し、
# $ALPHAFOLDDIR/bin/ ディレクトリを作成してそこに配置するのがおすすめ
############################################################

### set your environment module path
# . /usr/local/Modules/init/profile.sh
### require cuda 11.1 or later
# module load cuda/11.1.105

### set your alphafold directory
ALPHAFOLDDIR=/opt/alphafold

### set your database directory
DATABASEDIR=/data1/database

### ここまで設定事項。以下は変更の必要なし

. "${ALPHAFOLDDIR}/conda/etc/profile.d/conda.sh"
conda activate ${ALPHAFOLDDIR}/alphafold-conda
export TF_FORCE_UNIFIED_MEMORY=1
#export XLA_PYTHON_CLIENT_MEM_FRACTION=4.0
export XLA_PYTHON_CLIENT_MEM_FRACTION=4.0

### ユーザーからの引数に--model_preset=multimerが含まれた場合は
### 自動的にuniprot, pdb_seqresデータベースのパスを加える。
### そうでなければpdb70_database_pathを加える。
if [[ $* =~ "--model_preset=multimer" ]] ; then
  ADD_DB="--uniprot_database_path=$DATABASEDIR/uniprot/uniprot.fasta"
  ADD_DB="--pdb_seqres_database_path=$DATABASEDIR/pdb_seqres/pdb_seqres.txt $ADD_DB"
else
  ADD_DB="--pdb70_database_path=$DATABASEDIR/pdb70/pdb70"
fi

### run alphafold
python3.8 ${ALPHAFOLDDIR}/run_alphafold.py \
    --data_dir=$DATABASEDIR \
    --uniref90_database_path=$DATABASEDIR/uniref90/uniref90.fasta \
    --mgnify_database_path=$DATABASEDIR/mgnify/mgy_clusters_2018_12.fa \
    --bfd_database_path=$DATABASEDIR/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --uniclust30_database_path=$DATABASEDIR/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --template_mmcif_dir=$DATABASEDIR/pdb_mmcif/mmcif_files \
    --obsolete_pdbs_path=$DATABASEDIR/pdb_mmcif/obsolete.dat \
    --db_preset=full_dbs \
    --benchmark=False \
    --jackhmmer_binary_path=$ALPHAFOLDDIR/alphafold-conda/bin/jackhmmer \
    --hhblits_binary_path=$ALPHAFOLDDIR/alphafold-conda/bin/hhblits \
    --hhsearch_binary_path=$ALPHAFOLDDIR/alphafold-conda/bin/hhsearch \
    --kalign_binary_path=$ALPHAFOLDDIR/alphafold-conda/bin/kalign \
    $ADD_DB \
    --use_precomputed_msas \
$@

